#!/bin/zsh

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export GOPATH=$HOME/.local/share/go
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/.zshenv" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/.zshenv"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc" ] && . "${XDG_CONFIG_HOME:-$HOME/.config}/aliasrc"

eval "$(zoxide init zsh)"

[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Xorg >/dev/null && exec startx
